insert into GTVSM001.GTVTB004_DEPARTAMENTO (NU_DEPARTAMENTO, NO_NOME, IC_FIXO) values ((SELECT nextval('GTVSM001.GTVSQ005_DEPARTAMENTO')), 'Comercial', true);
insert into GTVSM001.GTVTB004_DEPARTAMENTO (NU_DEPARTAMENTO, NO_NOME, IC_FIXO) values ((SELECT nextval('GTVSM001.GTVSQ005_DEPARTAMENTO')), 'Faturamento', true);
insert into GTVSM001.GTVTB004_DEPARTAMENTO (NU_DEPARTAMENTO, NO_NOME, IC_FIXO) values ((SELECT nextval('GTVSM001.GTVSQ005_DEPARTAMENTO')), 'Financeiro', true);
insert into GTVSM001.GTVTB004_DEPARTAMENTO (NU_DEPARTAMENTO, NO_NOME, IC_FIXO) values ((SELECT nextval('GTVSM001.GTVSQ005_DEPARTAMENTO')), 'Notificações de Ocorrências', true);
insert into GTVSM001.GTVTB004_DEPARTAMENTO (NU_DEPARTAMENTO, NO_NOME, IC_FIXO) values ((SELECT nextval('GTVSM001.GTVSQ005_DEPARTAMENTO')), 'Operacional', true);
insert into GTVSM001.GTVTB004_DEPARTAMENTO (NU_DEPARTAMENTO, NO_NOME, IC_FIXO) values ((SELECT nextval('GTVSM001.GTVSQ005_DEPARTAMENTO')), 'Tesouraria​', true);